backend:
  image:
    repository: ghcr.io/infurox/aspecta-backend
    tag: aaa2f184e1a0bb4c7613cde24f4923821eec3a70
frontend:
  image:
    repository: ghcr.io/infurox/aspecta-frontend
    tag: aaa2f184e1a0bb4c7613cde24f4923821eec3a70
