backend:
  image:
    repository: ghcr.io/infurox/aspecta-backend
    tag: 158140c65247876999aac5a42a9f1face382513f
frontend:
  image:
    repository: ghcr.io/infurox/aspecta-frontend
    tag: 158140c65247876999aac5a42a9f1face382513f
